import SongStatePropertyUpdatedEvent from "./song_state_property_updated_event";

class FavoriteDeviceNamesUpdatedEvent extends SongStatePropertyUpdatedEvent {}

export default FavoriteDeviceNamesUpdatedEvent